language: python
python:
    - "3.6"

install:
    - pip install mysql-connector-python 
script:
    - python ./cloud/run_tests.py
notifications:
    email:
        - jj.lopezjaimez@gmail.com
        - delafuentegarza@gmail.com
        - j.limon.cabrera@gmail.com
        - A01175920@itesm.mx
